server:
  port: 8081

spring:
  application:
    name: e-commerce

  datasource:
    url: jdbc:h2:mem:e-commerce
    username: melinteteo
    password: ENC(dHolUsFv33uiPggjk7HxhPPwzaLHq/LiIPpeygBEtks=)

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
